### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TypicalModMaker** [mikigal/ConfigAPI#12]
```
java.lang.RuntimeException: Could not set max YAML line width
        at pl.mikigal.config.BukkitConfiguration.overrideMaxLineWidth(BukkitConfiguration.java:222) ~[BetterKingdoms.jar:?]
        at pl.mikigal.config.BukkitConfiguration.saveToString(BukkitConfiguration.java:113) ~[BetterKingdoms.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:65) ~[?:git-UniverseSpigot-"252422e"]
        at pl.mikigal.config.BukkitConfiguration.save(BukkitConfiguration.java:171) ~[BetterKingdoms.jar:?]
        at pl.mikigal.config.ConfigInvocationHandler.updateConfigFile(ConfigInvocationHandler.java:254) ~[BetterKingdoms.jar:?]
        at pl.mikigal.config.ConfigInvocationHandler.<init>(ConfigInvocationHandler.java:41) ~[BetterKingdoms.jar:?]
        at pl.mikigal.config.ConfigAPI.init(ConfigAPI.java:71) ~[BetterKingdoms.jar:?]
        at pl.mikigal.config.ConfigAPI.init(ConfigAPI.java:91) ~[BetterKingdoms.jar:?]
        at dev.isnow.betterkingdoms.config.ConfigManager.init(ConfigManager.java:27) ~[BetterKingdoms.jar:?]
        at dev.isnow.betterkingdoms.config.ConfigManager.<init>(ConfigManager.java:22) ~[BetterKingdoms.jar:?]
        at dev.isnow.betterkingdoms.BetterKingdoms.onEnable(BetterKingdoms.java:44) ~[BetterKingdoms.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[?:git-UniverseSpigot-"252422e"]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[?:git-UniverseSpigot-"252422e"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[?:git-UniverseSpigot-"252422e"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[?:git-UniverseSpigot-"252422e"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:642) ~[?:git-UniverseSpigot-"252422e"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:553) ~[?:git-UniverseSpigot-"252422e"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[?:git-UniverseSpigot-"252422e"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[?:git-UniverseSpigot-"252422e"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[?:git-UniverseSpigot-"252422e"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1139) ~[?:git-UniverseSpigot-"252422e"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324) ~[?:git-UniverseSpigot-"252422e"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NoSuchFieldException: yamlOptions
        at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
        at pl.mikigal.config.BukkitConfiguration.overrideMaxLineWidth(BukkitConfiguration.java:217) ~[BetterKingdoms.jar:?]
        ... 22 more
```

```java
@Getter
public class ConfigManager {
    private final DatabaseConfig databaseConfig;

    public ConfigManager(BetterKingdoms plugin) {
        // Another api issue...
        ConfigAPI.registerSerializer(DatabaseType.class, new DatabaseTypeSerializer());

        databaseConfig = (DatabaseConfig) init(DatabaseConfig.class, false, plugin);
    }

    private Config init(final Class<? extends Config> clazz, final boolean color, final BetterKingdoms plugin) {
        return ConfigAPI.init(
                (Class<? extends Config>) clazz,
                NameStyle.CAMEL_CASE,
                CommentStyle.INLINE,
                color,
                plugin
        );
    }
}
```

```java
public enum DatabaseType {
    MYSQL,
    MARIADB,
    H2,
    POSTGRES,
    SQLite,
    Oracle;
}
```

```java
@ConfigName("database.yml")
public interface DatabaseConfig extends Config {
    void setDatabase(Database database);

    default Database getDatabase() {
        return new Database("127.0.0.1", "sa", "", "betterkingdoms", DatabaseType.H2);
    }
}
```

```java
@Getter
@Setter
public class Database implements Serializable {
    private String ip;
    private String username;
    private String password;
    private String databaseName;
    private DatabaseType databaseType;

    public Database() {} // Config system stuff

    public Database(final String ip, final String username, final String password, final String databaseName, final DatabaseType databaseType) {
        this.ip = ip;
        this.username = username;
        this.password = password;
        this.databaseName = databaseName;
        this.databaseType = databaseType;
    }
}
```

Also another issue, I have to write a serlizers for enums because apparently it can't find a default constructor for them
```java
public class DatabaseTypeSerializer extends Serializer<DatabaseType> {
    @Override
    protected void saveObject(final String s, final DatabaseType databaseType, final BukkitConfiguration bukkitConfiguration) {
        bukkitConfiguration.set(s, databaseType.toString().toUpperCase(Locale.ROOT));
    }

    @Override
    public DatabaseType deserialize(final String s, final BukkitConfiguration bukkitConfiguration) {
        return DatabaseType.valueOf(bukkitConfiguration.getString(s).toUpperCase(Locale.ROOT));
    }
}
```

**Comment by TypicalModMaker** [comment]
Im using 1.20.4, its called yamlDumperOptions not yamlOptions here

**Comment by mikigal** [comment]
Thanks for report and PR!
Fix: https://github.com/mikigal/ConfigAPI/commit/d6a338b019619cfba8233fe54323f8009cae5b52
Implemented Enum support: https://github.com/mikigal/ConfigAPI/commit/745c5059aa632f349ff30b9e3fa7e7f9315a842a
