### ISSUE TITLE
Enum Support broken

### ISSUE THREAD

**Issue by TypicalModMaker** [mikigal/ConfigAPI#14]
```
[21:19:11 ERROR]: Error occurred while enabling BetterKingdoms vALPHA (Is it up to date?)
java.lang.NullPointerException: null
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at pl.mikigal.config.serializer.java.EnumSerializer.deserialize(EnumSerializer.java:33) ~[BetterKingdoms.jar:?]
        at pl.mikigal.config.serializer.java.EnumSerializer.deserialize(EnumSerializer.java:17) ~[BetterKingdoms.jar:?]
        at pl.mikigal.config.serializer.universal.UniversalObjectSerializer.deserialize(UniversalObjectSerializer.java:120) ~[BetterKingdoms.jar:?]
        at pl.mikigal.config.serializer.universal.UniversalObjectSerializer.deserialize(UniversalObjectSerializer.java:24) ~[BetterKingdoms.jar:?]
        at pl.mikigal.config.ConfigInvocationHandler.executeGetter(ConfigInvocationHandler.java:118) ~[BetterKingdoms.jar:?]
        at pl.mikigal.config.ConfigInvocationHandler.<init>(ConfigInvocationHandler.java:48) ~[BetterKingdoms.jar:?]
        at pl.mikigal.config.ConfigAPI.init(ConfigAPI.java:71) ~[BetterKingdoms.jar:?]
        at pl.mikigal.config.ConfigAPI.init(ConfigAPI.java:91) ~[BetterKingdoms.jar:?]
        at dev.isnow.betterkingdoms.config.ConfigManager.init(ConfigManager.java:32) ~[BetterKingdoms.jar:?]
        at dev.isnow.betterkingdoms.config.ConfigManager.<init>(ConfigManager.java:26) ~[BetterKingdoms.jar:?]
        at dev.isnow.betterkingdoms.BetterKingdoms.onEnable(BetterKingdoms.java:41) ~[BetterKingdoms.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[?:git-UniverseSpigot-"252422e"]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[?:git-UniverseSpigot-"252422e"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[?:git-UniverseSpigot-"252422e"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[?:git-UniverseSpigot-"252422e"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:642) ~[?:git-UniverseSpigot-"252422e"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:553) ~[?:git-UniverseSpigot-"252422e"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[?:git-UniverseSpigot-"252422e"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[?:git-UniverseSpigot-"252422e"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[?:git-UniverseSpigot-"252422e"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1139) ~[?:git-UniverseSpigot-"252422e"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324) ~[?:git-UniverseSpigot-"252422e"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

```java
@ConfigName("database.yml")
public interface DatabaseConfig extends Config {
    default Database getDatabase() {
        return new Database("127.0.0.1", "sa", "", "betterkingdoms", Platform.H2);
    }
}

@Getter
@Setter
@AllArgsConstructor
public class Database implements Serializable {
    private String ip;
    private String username;
    private String password;
    private String databaseName;
    private Platform databaseType;

    public Database() {} // Config system stuff
}

public enum Platform {
    GENERIC,
    CUSTOM,
    DB2,
    DB2FORI(DB2),
    DB2LUW(DB2),
    DB2LUW9(DB2),
    DB2ZOS(DB2),
    COCKROACH,
    CLICKHOUSE,
    H2,
    HSQLDB,
    POSTGRES,
    POSTGRES9(POSTGRES),
    MYSQL,
    MYSQL55(MYSQL),
    MARIADB,
    NUODB,
    ORACLE,
    ORACLE11(ORACLE),
    ORACLE12(ORACLE),
    ORACLE18(ORACLE),
    ORACLE21(ORACLE),
    SQLANYWHERE,
    SQLITE,
    SQLSERVER,
    SQLSERVER16(SQLSERVER),
    SQLSERVER17(SQLSERVER),
    HANA,
    YUGABYTE;

    private final Platform base;

    private Platform() {
        this.base = this;
    }

    private Platform(Platform base) {
        this.base = base;
    }

    public Platform base() {
        return this.base;
    }
}
```

**Comment by TypicalModMaker** [comment]
nevermind, looks like if the section is null it doesnt autoupdate to the default value

**Comment by mikigal** [comment]
What do you mean by section?
Please upload yaml file which cause this exception

**Comment by TypicalModMaker** [comment]
If i delete the enum section entirely, it throws provided error
Example:

database:
  ip: REDACTED
  username: REDACTED
  password: 'REDACTED'
  databaseName: isnow_test
  type: dev.isnow.betterkingdoms.config.impl.database.Database

**Comment by mikigal** [comment]
If you have a serializable object (Enum in this case) within another serializable object (Database in this case), it will not regenerate the value automatically.

Automatic generation is supported only for root elements
